### PR TITLE
Fix Command Sender error message

### LINKED ISSUE #1505: Command Sender command history error reporting
If you send a command from command history which contains an error (e.g. parameter out of range) the error message reflects the currently selected command from the drop downs instead of the actual command sent.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1505

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue [hunk 1]
```diff
@@ -774,9 +798,13 @@ export default {
       this.sendDisabled = false
     },
 
-    processCmdResponse(cmd_sent, response) {
+    processCmdResponse(success, targetName, commandName, cmd_sent, response) {
+      // If it was sent from history it's all in targetName, see sendCmd for details
+      if (commandName === undefined) {
+        ;[targetName, commandName] = targetName.split(' ').slice(0, 2)
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue:804]: Why does this have a leading semicolon?

**Review by ryanmelt — APPROVED** [review]

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-cmdsender/src/tools/CommandSender/CommandSender.vue:804]: https://prettier.io/docs/en/rationale.html#semicolons
