### PR TITLE
Hash as_json handle unlimited items

### LINKED ISSUE #863: Stack to deep upon loading plugin.
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
I have a target in my plugin that has one message that has a repeated set of 2048 structs with 100 fields. In total 204800 fields.  The intent was to create a screen or graph the data fields for each entry we were interested.  I could load it as a TLM file in the non-containerized 4.4 version of cosmos.  But in 5.5.1 the plugin installation crashes with a message "stack to deep".  Not sure if I am hitting some upper limit for the containerized version, or if there is an adjustment for it.  I know opening the TLM packet would lag with a message that size, but the intent was to create a screen that just looks at the fields I was interested in, but be able to log the whole data set for that frame.  

**To Reproduce**

I created a target with one cmd_tlm message with a loop of 2048 over 100 fields adding the index as part of the parameter name. So each of the sets of 100 would have the index appended to the name.  For example:

TELEMETRY <%= target_name %> MSG_NAME LITTLE_ENDIAN ""
APPEND_ID_ITEM MSG_ID 32 UINT 4002 "Packet ID"
APPEND_ITEM HEADER_MSG_ID 32 UINT ""
APPEND_ITEM HEADER_MSG_SIZE 32 UINT ""
<% 0.upto(2048) do | idx | %>
APPEND_ITEM field_X1_<%= idx %> 64 UINT ""
APPEND_ITEM field_X2_<%= idx %> 64 UINT ""
.
.
APPEND_ITEM field_X100_<%= idx %> 64 UINT ""
<% end %>

**Expected behavior**
I thought it would load, possibly laggy, but at least load so we could make a screen to look at what we needed to see.  Not sure if there is a better way to do what I am trying to add, or if its just too big and we need to break up the information somehow such as send smaller chunks more often. 

**Screenshots**

**Environment (please complete the following information):**
Red Hat Enterprise Linux 8.8 (Ootpa)
Podman 4.4
Firefox Extended Support Release 102.13.Oesr
Using cosmos_project release containers 5.5.1

### PR DESCRIPTION
**Pull request by jmthomas**
closes #863

### CODE REVIEW

**Comment by jmthomas** [comment]
Screenshot 2023-10-17 at 1 22 58 PM

File: openc3/lib/openc3/io/json_rpc.rb [hunk 1]
```diff
@@ -115,9 +115,9 @@ def as_json(options = nil) #:nodoc:
 
 class Hash
   def as_json(options = nil) #:nodoc:
-    pairs = []
-    self.each { |k, v| pairs << k.to_s; pairs << v.as_json(options) }
-    Hash[*pairs]
```
Comment (jmthomas) [inline openc3/lib/openc3/io/json_rpc.rb:120]: This was overwhelming the stack with the huge amount of items and causing a 'Stack too deep' error.

**Review by ryanmelt — APPROVED** [review]
