### PR TITLE
Ensure target_file returns utf-8 files

### LINKED ISSUE #1793: Can't open long edited suite, AXIOS error
**Describe the bug**
We have a long test suite (~600 lines) which runs over hours that we will edit portions of and re-run. Sometimes, however, when we try to open it (we see the asterisk denoting it has been edited from the plugin version) we get an axios error and it won't load. We do have local mode enabled so  when we hit this error, we move the file out of targets modified and then we can open the original plugin file.

image

This doesn't seem to happen on shorter files.

the docker container runs with the same user as owns the targets modified directories

**To Reproduce**

1. In script runner, edit a long file (\~600 lines)
2. run it for awhile (\~20 min to hour). Maybe disconnect network and reconnect
3. close tab, open new script runner tab
4. Try to open the file
5. See error above

**Expected behavior**
I should be able to open, edit, and run the file with no errors

**Environment (please complete the following information):**

- OS: RHEL9
- OpenC3 COSMOS Version 5.20.0
- Browser: Edge

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1793

### CODE REVIEW

File: openc3/lib/openc3/utilities/target_file.rb [hunk 1]
```diff
@@ -107,7 +107,7 @@ def self.body(scope, name)
         if File.extname(name) == ".bin"
           resp.body.binmode
         end
-        resp.body.read
+        resp.body.read.force_encoding('UTF-8')
```
Comment (ryanmelt) [inline openc3/lib/openc3/utilities/target_file.rb:110]: Don't do this if .bin

File: openc3/lib/openc3/utilities/target_file.rb [hunk 2]
```diff
@@ -94,7 +94,7 @@ def self.body(scope, name)
       # First try opening a potentially modified version by looking for the modified target
       if ENV['OPENC3_LOCAL_MODE']
         local_file = OpenC3::LocalMode.open_local_file(name, scope: scope)
-        return local_file.read if local_file
+        return local_file.read.force_encoding('UTF-8') if local_file
```
Comment (ryanmelt) [inline openc3/lib/openc3/utilities/target_file.rb:97]: Don't do this if .bin

**Review by ryanmelt — CHANGES_REQUESTED** [review]

**Review by ryanmelt — APPROVED** [review]
