### PR TITLE
Fix ScriptRunner Execute text when file modified

### LINKED ISSUE #1488: Execute Selection and Run From Here Can Complete Too Fast...
Using these methods sometimes the script completes before the new browser tab can even render causing, script doesn't exist type errors.

Maybe handle connecting to a completed script and just saying it looks like it already completed cleanly?

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1488

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue [hunk 1]
```diff
@@ -1358,6 +1358,12 @@ export default {
     },
     async executeText(text, breakpoints = []) {
       let extension = this.fullFilename.split('.').pop()
+      if (extension.includes(' *')) {
+        extension = extension.split(' *')[0]
+      }
+      if (extension !== 'rb' && extension !== 'py') {
+        extension = 'rb' // Still default to Ruby if we can't determine
+      }
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue:1366]: After testing I think the real issue was we were pushing files with `.rb *` in the filename and then the file could not be found.

Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue:1366]: Note that if the file completes early and we hit a route like `/tools/scriptrunner/99` we already open up the Completed Scripts pane and show that. Now that we have the ID in the completed scripts it should be easy to make the connection.

**Review by ryanmelt — APPROVED** [review]
