### PR TITLE
Convert db column to correct type

### LINKED ISSUE #2285: TSDB Playback on Derived Mnemonics
With the following screen:
```
SCREEN AUTO AUTO 1.0

VERTICAL
  VERTICALBOX "Header"
    LABELVALUE INST LATEST TEMP1HIGH
  END
END
```

And running playback, it seems like derived mnemonics are not properly handled in the TSDB query. The error:
```
Error querying QuestDB: ERROR:  Invalid column: T0.TEMP1HIGH__C\nLINE 1: SELECT \"T0.TEMP1HIGH__C\" FROM INST__HEALTH_STATUS as T0 WHER...\n
```
is presented. Likely, it's because of the logic of figuring out the converted, with units, or formatted versions (this derived mnemonic only has the TEMP1HIGH in the quest table, without the *_C, *_F, etc)

** Sparkline also having some issues

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2285

### CODE REVIEW

**Comment by clayandgen** [comment]
I used this screen:
```
SCREEN AUTO AUTO 1.0

VERTICAL
  VERTICALBOX "Header"
    LABELVALUE INST LATEST TEMP1HIGH
  END
END
```
and I think I'm still seeing the issue 🤔 

also -- does this address the sparkline issue? I don't see sparklines populate with the following screen:
```
SCREEN AUTO AUTO 1.0

VERTICAL
  VERTICALBOX "Header"
    SPARKLINE INST HEALTH_STATUS TEMP1
      SETTING SIZE 400 50
      SETTING HISTORY 30s
  END
END
```

**Comment by jmthomas** [comment]
I didn't check the Sparkline ... forgot about that addition to the ticket. I'll double check your telemetry point and verify Sparkline functionality.

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue [hunk 1]
```diff
@@ -1028,6 +1028,13 @@ export default {
       const screenItems = this.itemSubscriptionKeys.map((key) => {
         return key.split('__').slice(2).join('__')
       })
+      if (this.actualXAxisItem === DEFAULT_X_AXIS_ITEM) {
+        // We always need time if using the default x-axis item
+        screenItems.unshift('INST__HEALTH_STATUS__PACKET_TIMESECONDS__RAW')
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue]: Uh. INST HEALTH_STATUS?

File: openc3/python/openc3/microservices/quest_microservice.py [hunk 2]
```diff
@@ -263,8 +263,41 @@ def read_topics(self):
...
+                        else:
+                            self.logger.error("QuestDB: Could not parse table, column, or type from error message")
+                            return
+
+                        # Try to change the column type to fix the error
+                        # We put the table in double quotes to handle special characters
+                        alter = f"""ALTER TABLE "{table_name}" ALTER COLUMN {column_name} TYPE {column_type}"""
+                        cur.execute(alter)
+                        self.logger.info(f"QuestDB: {alter}")
+                        self.connect_ingest() # reconnect
```
Comment (ryanmelt) [inline openc3/python/openc3/microservices/quest_microservice.py:294]: Retry failed write here?

**Review by ryanmelt — CHANGES_REQUESTED** [review]

File: openc3/python/openc3/microservices/quest_microservice.py (hunk 2 above)
Comment (jmthomas) [reply openc3/python/openc3/microservices/quest_microservice.py:294]: Added retry

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/components/Graph.vue]: Fixed
