### PR TITLE
Add warning about unmerged diffs and fix diff logic

### LINKED ISSUE #1015: Add Are you Sure when diffs aren't incorporated in plugin upgrade
Also diffs still sometimes copy over on the wrong line...

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1015

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/diff-match-patch.js [hunk 1]
```diff
@@ -218,23 +219,24 @@ diff_match_patch.prototype.diff_compute_ = function (
...
-    // Send both pairs off for separate processing.
-    var diffs_a = this.diff_main(text1_a, text2_a, checklines, deadline)
-    var diffs_b = this.diff_main(text1_b, text2_b, checklines, deadline)
-    // Merge the results.
-    return diffs_a.concat(
-      [new diff_match_patch.Diff(DIFF_EQUAL, mid_common)],
-      diffs_b
-    )
-  }
+  // JMT: This doesn't always return a good result so commenting it out
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/diff-match-patch.js:222]: Near as I can tell this was just an optimization

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/diff-match-patch.js [hunk 2]
```diff
@@ -1020,6 +1022,13 @@ diff_match_patch.prototype.diff_cleanupSemanticLossless = function (diffs) {
       // First, shift the edit as far left as possible.
       var commonOffset = this.diff_commonSuffix(equality1, edit)
       if (commonOffset) {
+        // JMT: If the end of the common suffix is a newline then
+        // keep the newline because we want to favor trailing newlines
+        // to support the common use case of adding a line. Otherwise the
+        // algorithm shifts left to include the leading newline.
+        if (equality1[equality1.length - commonOffset] === '\n') {
+          commonOffset -= 1
+        }
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/diff-match-patch.js:1031]: This is what was breaking the common diff use case of inserting a line. A diff of `added code\n` became `\nadded code`

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/index.js [hunk 3]
```diff
@@ -368,10 +375,11 @@ function copy(acediff, e, dir) {
...
   for (let i = startLine; i < endLine; i += 1) {
     contentToInsert += getLine(sourceEditor, i)
-    // If the first line is blank we add an extra newline
+    // JMT: If the first line is blank we add an extra newline
     // because when it is inserted the first one is effectively eaten
     // by the replace and merging of the lines
-    if (i === startLine && contentToInsert === '') {
+    // However if the targetStartLine is the very top then we don't
+    if (i === startLine && contentToInsert === '' && targetStartLine != 0) {
       contentToInsert += '\n'
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-ace-diff/src/index.js:383]: I think I added this a while ago and while it's needed in some cases it doesn't work if inserting at the very top.

**Review by ryanmelt — APPROVED** [review]
