### PR TITLE
Default various SETTINGS to px

### LINKED ISSUE #474: Telemetry screen WIDTH setting not working in 5.4.2
**Describe the bug**
Telemetry screen widget WIDTH settings are not applying when displayed. Widgets are using their default widths instead.
This setting previously worked in 5.3.0, but stopped working when I upgraded to 5.4.2.

**To Reproduce**
Create a telemetry screen with custom widget WIDTH settings either using GLOBAL_SETTING or SETTING

**Expected behavior**
The widget widths are set to the defined value when displayed.

**Environment (please complete the following information):**

- OS: Windows 10
- OpenC3 COSMOS Version: 5.4.2
- Browser: Google Chrome

### PR DESCRIPTION
**Pull request by jmthomas**
closes #474

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js [hunk 1]
```diff
@@ -62,10 +62,16 @@ export default {
             style['text-align'] = setting[1].toLowerCase()
             break
           case 'PADDING':
-            style['padding'] = setting[1] + 'px !important'
+            if (!isNaN(Number(setting[1]))) {
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/Widget.js:65]: This is an interesting way of detecting mixed numbers and text.

**Review by ryanmelt — APPROVED** [review]
