### PR TITLE
RECEIVED_COUNT returns 0 if packet not received

### LINKED ISSUE #1494: RECEIVED_COUNT on a packet which has never been received should return 0 not nil/null
If a packet has never been received, the received count value currently is null or nil. It would be more intuitive for this value to report 0.

In my case, I have a NAK packet that is returned for a variety of commanding errors. I want to verify that is zero.
```
# Verify NAK is zero. This doesn't work.
check("UUT NAK RECEIVED_COUNT == 0")

# Verify NAK is zero. This DOES work but is less readable.
check_expression("tlm('UUT NAK RECEIVED_COUNT').nil?")
```

Tested on COSMOS 5.18.0 in Chrome

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1494

### CODE REVIEW

File: openc3/lib/openc3/models/cvt_model.rb [hunk 1]
```diff
@@ -100,15 +100,21 @@ def self.get_item(target_name, packet_name, item_name, type:, cache_timeout: nil
...
+            return cvt_value.to_s
           end
-          return result
+          return cvt_value
         end
       end
-      return nil
+      # RECEIVED_COUNT is a special case where it is 0 if it doesn't exist
+      # This allows scripts to check against the value to see if the packet was ever received
+      if types[-1] == "RECEIVED_COUNT"
```
Comment (ryanmelt) [inline openc3/lib/openc3/models/cvt_model.rb:113]: What is types[-1]?  Shouldn't this be item_name?

File: openc3/python/openc3/models/cvt_model.py [hunk 2]
```diff
@@ -127,12 +127,17 @@ def get_item(
...
+            if cvt_value is not None:
                 if type == "FORMATTED" or type == "WITH_UNITS":
-                    return str(result)
-                return result
-        return None
+                    return str(cvt_value)
+                return cvt_value
+        # RECEIVED_COUNT is a special case where it is 0 if it doesn't exist
+        # This allows scripts to check against the value to see if the packet was ever received
+        if types[-1] == "RECEIVED_COUNT":
```
Comment (ryanmelt) [inline openc3/python/openc3/models/cvt_model.py:137]: Ditto.

**Review by ryanmelt — CHANGES_REQUESTED** [review]

File: openc3/lib/openc3/models/cvt_model.rb (hunk 1 above)
Comment (jmthomas) [reply openc3/lib/openc3/models/cvt_model.rb:113]: types is set by `_handle_item_override` but yes `item_name` is a better choice
