### PR TITLE
Fix spacer widget

### LINKED ISSUE #1550: SPACER widget not working
SPACER widget doesn't appear to be adding any spacing

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1550

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/SpacerWidget.vue [hunk 1]
```diff
@@ -21,7 +21,7 @@
 -->
 
 <template>
-  <div :style="style" />
+  <div :style="localStyle" />
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/SpacerWidget.vue:24]: Any idea why a simple name change fixed this?

Comment (ryanmelt) [reply openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/widgets/SpacerWidget.vue:24]: Style is defined in the Widget.js mixin.   Please evaluate and make sure that is working like expected.

**Review by ryanmelt — CHANGES_REQUESTED** [review]

**Comment by jmthomas** [comment]
This definition:
```
SCREEN AUTO AUTO 1.0

HORIZONTALBOX "Horizontal LEDs"
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
  SPACER
    SETTING WIDTH 100
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
  SPACER 50 0
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
END

VERTICALBOX "Vertical LEDs"
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
  SPACER
    SETTING HEIGHT 100
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
  SPACER 50 50
  LED INST PARAMS VALUE5 
    SETTING LED_COLOR GOOD GREEN
    SETTING LED_COLOR BAD RED
END
```
results in this:
Screenshot 2024-09-19 at 6 42 57 PM

**Review by ryanmelt — APPROVED** [review]
