### PR TITLE
Fix script connect error if completed

### LINKED ISSUE #2071: v6.4.0 Script Runner Stuck on "Connecting..."
Script runner gets stuck on "Connecting..." if the script ends while the screen is not on Script Runner.

- Create a new script with `wait(10)`
- Click on a different Tool 
- Wait 11 seconds
- Click back onto Script Runner to get the stuck state

Image

### PR DESCRIPTION
**Pull request by jmthomas**
closes #2071

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/RunningScripts.vue [hunk 1]
```diff
@@ -210,7 +210,7 @@ export default {
     return {
       api: null,
       timeZone: 'local',
-      activeTab: 'running',
+      activeTab: 'completed',
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/RunningScripts.vue:213]: Shouldn't showing the running scripts be the default?

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue [hunk 2]
```diff
@@ -1283,10 +1283,10 @@ export default {
         if (response.data) {
           let state = response.data.state
           if (
-            state !== 'complete' &&
-            state !== 'complete_errors' &&
+            state !== 'completed' &&
+            state !== 'completed_errors' &&
             state !== 'stopped' &&
-            state !== 'crash' &&
+            state !== 'crashed' &&
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/ScriptRunner.vue:1289]: Ah.  Oops.  I missed changes these to the 'ed' versions

**Review by ryanmelt — CHANGES_REQUESTED** [review]

File: openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/RunningScripts.vue (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-init/plugins/packages/openc3-vue-common/src/tools/scriptrunner/RunningScripts.vue:213]: I think most users want to see completed scripts because they're not migrating away from the current running script.

File: openc3/lib/openc3/models/script_status_model.rb [hunk 3]
```diff
@@ -208,9 +208,9 @@ def update(force: false, queued: false)
     def destroy
       @destroyed = true
       undeploy()
-      self.class.store.hdel(@primary_key, @name)
+      self.class.store_queued.hdel(@primary_key, @name)
```
Comment (ryanmelt) [inline openc3/lib/openc3/models/script_status_model.rb:211]: Should take a queued argument like create and use the right one accordingly.

File: openc3/python/openc3/models/script_status_model.py [hunk 4]
```diff
@@ -179,9 +179,9 @@ def update(self, force = False, queued = False):
     def destroy(self):
         self.destroyed = True
         self.undeploy()
-        self.store().hdel(self.primary_key, self.name)
+        self.store_queued().hdel(self.primary_key, self.name)
```
Comment (ryanmelt) [inline openc3/python/openc3/models/script_status_model.py:182]: Should take a queued argument like create and use the right one accordingly.

**Review by ryanmelt — CHANGES_REQUESTED** [review]

File: openc3/lib/openc3/models/script_status_model.rb (hunk 3 above)
Comment (jmthomas) [reply openc3/lib/openc3/models/script_status_model.rb:211]: There's only right one: queued. Otherwise you might get out of order when doing the delete.

Comment (ryanmelt) [reply openc3/lib/openc3/models/script_status_model.rb:211]: In the current code yes.   In the future who knows. It should be an argument just like for create. and pass true in the current use.

**Review by ryanmelt — APPROVED** [review]
