### PR TITLE
Deploy new scopes

### LINKED ISSUE #1276: Text logs on some scopes don't get saved
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
On multiple of our cosmos servers, I have noticed that text logs are not being saved to minio on all scopes except default, even though log configuration is the same on each server.

**To Reproduce**

1. Create a Cosmos server with multiple scopes.
2. Run commands on server to generate logs.
3. Note that some scopes do not save text logs to minio.

**Expected behavior**
I expect that each scope should save off text logs to minio automatically.

**Screenshots**
image
image

**Environment (please complete the following information):**

- OS: Linux Ubuntu 22.04.2 LTS
- OpenC3 COSMOS Version 5.9.0
- Browser: Chrome

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1276

### CODE REVIEW

File: openc3-cosmos-cmd-tlm-api/app/controllers/scopes_controller.rb [hunk 1]
```diff
@@ -35,7 +35,16 @@ def index
...
   def create(update_model = false)
     return unless authorization('superadmin')
-    super(update_model)
+    model = @model_class.from_json(params[:json], scope: params[:scope])
+    if update_model
+      model.update
+      OpenC3::Logger.info("#{@model_class.name} updated: #{params[:json]}", scope: params[:scope], user: username())
+    else
+      model.create
+      model.deploy
```
Comment (ryanmelt) [inline openc3-cosmos-cmd-tlm-api/app/controllers/scopes_controller.rb:44]: Deploy has two required arguments.   You can pass "." and {} for these like in openc3cli.
model.deploy(".", {})

**Review by ryanmelt — CHANGES_REQUESTED** [review]
