### PR TITLE
Make json, cbor, xml, html enforce data types

### LINKED ISSUE #990: Data of type "FLOAT" is auto-converted to "INT" if there are no non-zero decimals
**Describe the bug**
If a user has a command definition with a parameter of type "FLOAT", and does not include a non-zero decimal in that parameter when sending the command, COSMOS will turn the value into an int. This is problematic for a protocol that utilizes CBOR within it, because the encoded type will be set an "int", rather than the appropriate "float". As of currently, workaround code is required to fix this (See below). Not sure if this is fixed in later COSMOS versions.

**To Reproduce**
with parameter name "timeout", type FLOAT, value -1.01:
cmd("SYSTEM START_TEST with INTERFACE 'my_interface', TIMEOUT -1.01")

with parameter name "timeout", type FLOAT, value -1.0:
cmd("SYSTEM START_TEST with INTERFACE 'my_interface', TIMEOUT -1")

**Screenshots**
image
image
image

Edit: Added another screenshot

**Environment (please complete the following information):**
- OS: Linux Ubuntu
- OpenC3 COSMOS Version: 5.8.1
- Browser: N/A

### PR DESCRIPTION
**Pull request by jmthomas**
closes #990

### CODE REVIEW

File: openc3/lib/openc3/accessors/accessor.rb [hunk 1]
```diff
@@ -92,33 +94,34 @@ def self.write_items(items, values, buffer)
...
+        if item.array_size
+          value = JSON.parse(value) if value.is_a? String
+          value = value.map(&:to_s)
+        else
+          value = value.to_s
+        end
+      when :UINT, :INT
+        if item.array_size
+          value = JSON.parse(value) if value.is_a? String
+          value = value.map(&:to_i)
```
Comment (ryanmelt) [inline openc3/lib/openc3/accessors/accessor.rb:110]: to_i and to_f do not handle as many cases as Integer() and Float().  ie hex

**Review by ryanmelt — CHANGES_REQUESTED** [review]

**Review by ryanmelt — APPROVED** [review]
