### PR TITLE
Properly parse hex and binary ID items

### LINKED ISSUE #1895: Parameter default value does not work for hexadecimal values
I have a command packet definition:
```log
COMMAND MC NOOP BIG_ENDIAN "..."
  APPEND_ID_PARAMETER CCSDS_STREAMID 16 UINT MIN MAX 0x1834 "CCSDS Packet Identification"
  APPEND_PARAMETER CCSDS_SEQUENCE    16 UINT MIN MAX 0xC000 "CCSDS Packet Sequence Control"
  APPEND_PARAMETER CCSDS_LENGTH      16 UINT MIN MAX 1 "CCSDS Packet Data Length"
  APPEND_PARAMETER CCSDS_FC           8 UINT MIN MAX 0 "CCSDS Command Function Code"
  APPEND_PARAMETER CCSDS_CHECKSUM     8 UINT MIN MAX 0 "Checksum"
```

The parameter CCSDS_STREAMID has a specified default of 0x1834. This is parsed out as a string, and in [packet_item.py:620](https://github.com/OpenC3/cosmos/blob/main/openc3/python/openc3/packets/packet_item.py#L620), this string is converted to an integer. This conversion fails due to assumed base 10:

```py
Exception: Error processing MC:
Traceback (most recent call last):
  File "/openc3/venv/lib/python3.11/site-packages/openc3/packets/packet_item.py", line 620, in convert
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0x1834'
```

Solution (?):
Replace
```py
return int(value)
```
with
```py
return int(value, 0)
```
Specifying the base of 0 is required in order to [decode strings with hex prefixes](https://docs.python.org/3/library/functions.html#int)

I am unsure why it is using the Python code to do this - I tested on 5.16.2 AND 5.20.1 and 6.1.0 and got the same results. Is there a way to use the ruby code for this instead as a temporary fix?

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1895

### CODE REVIEW

File: openc3/spec/packets/parsers/packet_item_parser_spec.rb [hunk 1]
```diff
@@ -127,18 +127,23 @@ module OpenC3
...
           tf.puts 'TELEMETRY tgt1 pkt1 LITTLE_ENDIAN "Description"'
-          tf.puts '  ID_ITEM ITEM1 0 32 INT 0'
+          tf.puts '  ID_ITEM ITEM1 0 32 INT 0x42'
           tf.puts '  ITEM ITEM2 0 32 UINT'
           tf.puts '  ARRAY_ITEM ITEM3 0 32 FLOAT 64'
-          tf.puts '  APPEND_ID_ITEM ITEM4 32 STRING "ABCD"'
-          tf.puts '  APPEND_ITEM ITEM5 32 BLOCK'
-          tf.puts '  APPEND_ARRAY_ITEM ITEM6 32 BLOCK 64'
+          tf.puts '  APPEND_ID_ITEM ITEM4 32 STRING "0xABCD"'
+          tf.puts '  APPEND_ID_ITEM ITEM5 32 BLOCK 0xABCD'
```
Comment (jmthomas) [inline openc3/spec/packets/parsers/packet_item_parser_spec.rb:134]: Ruby didn't support block ID items as binary

File: openc3/lib/openc3/packets/parsers/packet_item_parser.rb [hunk 2]
```diff
@@ -193,22 +197,25 @@ def get_default
...
-        # STRING and BLOCK PARAMETERS don't have min and max values
-        index -= 2 if data_type == :STRING || data_type == :BLOCK
-      end
       if data_type == :DERIVED
         raise @parser.error("DERIVED data type not allowed for Identifier")
       end
+      # For PARAMETERS the default value is the ID value
+      if @parser.keyword.include?("PARAMETER")
+        return item.default
+      end
```
Comment (jmthomas) [inline openc3/lib/openc3/packets/parsers/packet_item_parser.rb:209]: No need to reparse the ID value in commands ... just use the default

File: openc3/python/openc3/packets/parsers/packet_item_parser.py [hunk 3]
```diff
@@ -212,21 +215,25 @@ def _get_default(self):
...
-            index = 5 if self._append() else 6
-            # STRING and BLOCK PARAMETERS don't have min and max values
-            if data_type == "STRING" or data_type == "BLOCK":
-                index -= 2
         if data_type == "DERIVED":
             raise self.parser.error("DERIVED data type not allowed for Identifier")
-        return self.parser.parameters[index]
+        # For PARAMETERS the default value is the ID value
+        if "PARAMETER" in self.parser.keyword:
+            return item.default
```
Comment (jmthomas) [inline openc3/python/openc3/packets/parsers/packet_item_parser.py:226]: No need to reparse the ID value in commands ... just use the default

File: openc3/python/test/packets/parsers/test_packet_item_parser.py [hunk 4]
```diff
@@ -129,22 +129,27 @@ def test_only_allows_derived_items_with_offset_0_and_size_0(self):
     def test_accepts_types_int_uint_float_string_block(self):
         tf = tempfile.NamedTemporaryFile(mode="w")
         tf.write('TELEMETRY tgt1 pkt1 LITTLE_ENDIAN "Description"\n')
-        tf.write("  ID_ITEM ITEM1 0 32 INT 0\n")
+        tf.write("  ID_ITEM ITEM1 0 32 INT 0x42\n")
```
Comment (jmthomas) [inline openc3/python/test/packets/parsers/test_packet_item_parser.py:132]: This case currently fails in Python (but not Ruby) because Ruby calls `Integer(value)` which works ... the Python conversion code did not handle it.

**Review by ryanmelt — APPROVED** [review]
