### PR TITLE
Kill Microservice on any Thread Crash

### LINKED ISSUE #286: Thread.abort_on_exception not working fully
Thread.abort_on_exception raises the exception from the dying thread on the main thread.
This by itself does not guarantee that the whole process will die (as desired).
Main threads should just sleep and do nothing and not have exception handlers to ensure the desired behavior.

### LINKED ISSUE #391: Multi microservice doesn't die if an embedded microservice dies
This prevents the embedded microservice from being restarted, and can be more subtle than desired.

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #286 
closes #391

### CODE REVIEW

File: openc3/lib/openc3/microservices/microservice.rb [hunk 1]
```diff
@@ -192,6 +198,7 @@ def initialize(name, is_plugin: false)
           @logger.error "#{@name} status thread died: #{e.formatted}"
           raise e
         end
+        ThreadManager.instance.register(@microservice_status_thread)
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/microservice.rb:201]: Why are we running `@microservice_status_thread` and calling `MicroserviceStatusModel.set` here in initialize as well as in the `run` method. Seems like we're double booking it.

File: openc3/lib/openc3/packets/structure_item.rb [hunk 2]
```diff
@@ -303,6 +303,7 @@ def <=>(other)
     def clone
       item = super()
       item.name = self.name.clone if self.name
+      item.key = self.key.clone if self.key
```
Comment (jmthomas) [inline openc3/lib/openc3/packets/structure_item.rb:306]: Was this an old bug?

File: openc3/lib/openc3/utilities/thread_manager.rb [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+    def monitor
+      while true
+        @threads.each do |thread, _, _|
+          if !thread.alive?
+            return
+          end
+        end
+        sleep(MONITOR_SLEEP_SECONDS)
+      end
+    end
```
Comment (jmthomas) [inline openc3/lib/openc3/utilities/thread_manager.rb:58]: So we monitor until we detect a single thread is dead. This breaks the loop at which point we call `shutdown` and kill all the remaining threads.

File: openc3/python/openc3/packets/structure.py [hunk 4]
```diff
@@ -481,9 +481,24 @@ def buffer(self, buffer):
     def clone(self):
         struct = copy.copy(self)
         struct._buffer = self.buffer  # Makes a copy
+        struct.accessor = copy.copy(self.accessor)
         struct.accessor.packet = struct
         return struct
 
+    # Clone that also deep copies items
+    # @return [Structure] A deep copy of the structure
+    def deep_copy(self):
```
Comment (jmthomas) [inline openc3/python/openc3/packets/structure.py:490]: Python already has a `deepcopy` method: https://docs.python.org/3/library/copy.html

**Review by jmthomas — APPROVED** [review]
Can I get some unit tests for all this new functionality? :-)

**Review by jmthomas — CHANGES_REQUESTED** [review]
Looks like this was branched off #1901. That's ok I guess but I commented on some of that in this PR. Also we need some unit tests.

File: openc3/lib/openc3/packets/structure_item.rb (hunk 2 above)
Comment (ryanmelt) [reply openc3/lib/openc3/packets/structure_item.rb:306]: Sort of.  It makes it a more complete clone.

File: openc3/lib/openc3/utilities/thread_manager.rb (hunk 3 above)
Comment (ryanmelt) [reply openc3/lib/openc3/utilities/thread_manager.rb:58]: Correct.

File: openc3/python/openc3/packets/structure.py (hunk 4 above)
Comment (ryanmelt) [reply openc3/python/openc3/packets/structure.py:490]: Its a mostly deep copy.  Can't do a real deep copy at least in Ruby because of the Mutex

File: openc3/lib/openc3/microservices/microservice.rb (hunk 1 above)
Comment (ryanmelt) [reply openc3/lib/openc3/microservices/microservice.rb:201]: I don't think anything is double booked.

**Comment by ryanmelt** [comment]
Would love someone to add a unit test for ThreadManager ;)

**Review by jmthomas — APPROVED** [review]
Now with unit tests!
