### PR TITLE
Eliminate script zombies. Fix python output thread. Default CI to empty string

### LINKED ISSUE #1503: The ScriptRunner container leaves dead processes in the process list (ps -ef)
Linux calls these "zombie processes" which sounds scary, except they are completely dead but have left an entry in the process table.
The spawning process needs to properly cleanup when they complete some how.

I'm not sure if this is actually a problem besides cluttering the process table.   But maybe the system will eventually run out of process handles?

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #1503

### CODE REVIEW

File: openc3-cosmos-script-runner-api/app/models/running_script.rb [hunk 1]
```diff
@@ -396,6 +396,7 @@ def self.spawn(scope, name, suite_runner = nil, disconnect = false, environment
     process.environment['RUBYOPT'] = nil # Removes loading bundler setup
     process.environment['OPENC3_SCOPE'] = scope
 
+    process.detach = true
```
Comment (jmthomas) [inline openc3-cosmos-script-runner-api/app/models/running_script.rb:399]: This prevents zombie processes?

File: openc3-cosmos-script-runner-api/scripts/running_script.py [hunk 2]
```diff
@@ -1223,7 +1225,7 @@ def output_thread_body(self):
         while True:
             if RunningScript.cancel_output:
                 break
-            if (time.time() - self.output_time) > 5.0:
+            if (time.time() - self.output_time_value) > 5.0:
```
Comment (jmthomas) [inline openc3-cosmos-script-runner-api/scripts/running_script.py:1228]: Did my refactor break this or was it always broke?

**Review by jmthomas — APPROVED** [review]

File: openc3-cosmos-script-runner-api/app/models/running_script.rb (hunk 1 above)
Comment (ryanmelt) [reply openc3-cosmos-script-runner-api/app/models/running_script.rb:399]: Yes. Detaching means that the spawning process is not responsible for waiting for the child to die and check the exit status.

File: openc3-cosmos-script-runner-api/scripts/running_script.py (hunk 2 above)
Comment (ryanmelt) [reply openc3-cosmos-script-runner-api/scripts/running_script.py:1228]: I don't know.
