### PR TITLE
Py suite

### LINKED ISSUE #1715: Python import in a TestSuite
I submitted a previous ticket on this topic which was closed and indicated we should use COSMOS latest (5.20.0). We ran into a myriad of issues with 5.20.0 and thus are still on 5.17.1. Again the issue is we moved our scripting to Python from Ruby. When we want to import a python file, to be used by the test suite we get "ModuleNotFoundError: No module named 'TGT'". 

To produce this issue I create a new plugin with:
**opt/openc3/cosmos-5.17.1/openc3.sh cli generate plugin tgt**
Plugin openc3-cosmos-tgt successfully generated!

and a new target with:
**/opt/openc3/cosmos-5.17.1/openc3.sh cli generate target tgt --python**
Target TGT successfully generated!

I update my plugin and target files (provided below)
[plugin.txt](https://github.com/user-attachments/files/17817811/plugin.txt)
[target.txt](https://github.com/user-attachments/files/17817815/target.txt)

I build the plugin and deploy. In script runner I edit procedure.py to have the following:
**class HellowWorld:
  def print_hello_world(self):
    print("Hello World!")**

I then create a New Test Suite from template and add the line:
**from TGT.procedures.procedure import \***

This is where I get the error from above. This is effectively a generated default plugin with a small edit and Python importing doesn't work as the user guide indicates.

Thanks.

Ubuntu 22.04.4
Cosmos 5.17.1

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1715

### CODE REVIEW

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Remove revert of shard.

File: openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue [hunk 1]
```diff
@@ -623,6 +623,7 @@ export default {
 }
 .list {
   background-color: var(--color-background-surface-default) !important;
+  overflow-x: hidden;
```
Comment (jmthomas) [inline openc3-cosmos-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue:626]: This is to remove the horizontal scroll on the plugins tab
