### PR TITLE
Fix fileDialogCallback promise logic

### LINKED ISSUE #1487: File upload sometimes fails using open_file_dialog
**Describe the bug**
Occasionally, file uploads will fail when using the `open_file_dialog` method, with the error `HTTPClientException : 404 Not Found`. I believe is somehow caused by the dialog becoming "unlinked" from the code, as it is accompanied by this message upon hitting cancel: `INFO: Unexpectedly received answer for unknown prompt .`.

**To Reproduce**

Not sure of the exact reproducibility as it does not happen every time, but:
1. Create script with `upload_file_dialog` method
2. Upload file
3. File upload fails

**Expected behavior**
File should upload successfully every time.

**Screenshots**
image
image

**Environment (please complete the following information):**

- OS: Windows 11, COSMOS server running on Ubuntu 22.04.1
- OpenC3 COSMOS Version: 5.17.1
- Browser: Chrome and Firefox

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1487

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue [hunk 1]
```diff
@@ -1957,30 +1957,44 @@ export default {
...
-        data: {
-          method: this.file.multiple ? 'open_files_dialog' : 'open_file_dialog',
-          answer: fileNames,
-          prompt_id: this.activePromptId,
-        },
+
+      // We have to wait for all the upload API requests to finish before notifying the prompt
+      Promise.all(promises).then((responses) => {
+        // eslint-disable-next-line
+        console.log('post prompt')
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-cosmos-tool-scriptrunner/src/tools/ScriptRunner/ScriptRunner.vue:1988]: Remove debug console print

**Review by ryanmelt — CHANGES_REQUESTED** [review]

**Review by ryanmelt — APPROVED** [review]
