### PR TITLE
Fix download_file and get_target_file

### LINKED ISSUE #1142: Python formatted does not work for get_target_file() read
I have a Python script that reads from a target's binary file. I tried to follow the instructions [here](https://docs.openc3.com/docs/guides/scripting-api#get_target_file) for Python, using something very similar:
```py
file = get_target_file(f"RCE/returns/capture/{name.lower()}_{channel}.bin")
print(formatted(file.read()))
```

This gets the following error:
```
2024-03-13T17:16:47.495877Z (generate_return_plots.py:12): {"time": 1.710350207495877e+18, "@timestamp": "2024-03-13T17:16:47.495877Z", "level": "ERROR", "microservice_name": "Script Runner", "detail": "generate_return_plots.py:12", "container_name": "14bd866567c3", "message": "Traceback (most recent call last):\n File \"RCE/lib/generate_return_plots.py\", line 12, in plot\n print(formatted(file.read()))\n ^^^^^^^^^^^^^^^^^^^^^^\n File \"/usr/lib/python3.11/site-packages/openc3/utilities/string.py\", line 66, in formatted\n string += \"%02X\" % byte\n ~~~~~~~^~~~~~\nTypeError: %X format: an integer is required, not str\n", "type": "log"}
```

I believe this has something to do with how the file is read out using `get_target_file()`, maybe [this](https://github.com/OpenC3/cosmos/blob/e555b5ba4127590bcedf79edf486babb8829869e/openc3/python/openc3/script/storage.py#L108)? Opening the file in text mode might be causing unexpected behavior.

OpenC3 COSMOS Version 5.15.0

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1142

### CODE REVIEW

File: openc3-cosmos-script-runner-api/app/models/running_script.rb [hunk 1]
```diff
@@ -166,7 +166,7 @@ def openc3_script_sleep(sleep_time = nil)
         return false
       end
 
-      def display_screen(target_name, screen_name, x = nil, y = nil, scope: $openc3_scope)
+      def display_screen(target_name, screen_name, x = nil, y = nil, scope: RunningScript.instance.scope)
```
Comment (ryanmelt) [inline openc3-cosmos-script-runner-api/app/models/running_script.rb:169]: why scope change?

**Review by ryanmelt — APPROVED** [review]

File: openc3-cosmos-script-runner-api/app/models/running_script.rb (hunk 1 above)
Comment (jmthomas) [reply openc3-cosmos-script-runner-api/app/models/running_script.rb:169]: I don't think it was correct. If you look at the rest of the file the scope should be coming from the `RunningScript.instance.scope`. It can still be manually overridden but I think that's the correct default.
