### PR TITLE
Prevent loading previous script on script run

### LINKED ISSUE #746: Script Runner opening script a suite when script is called from a button
**Describe the bug**
When running a script from a button on a screen the script runner opened the script as a suite. Seems to be related to the fact that whenever you open a script runner now it opens up the previous script.

**To Reproduce**

1. Run/open a suite in script runner
2. Close out of the script runner 
3. Run a script from a button in telemetry viewer

**Expected behavior**
If the button calls a script it should not produce the options that suites have image 1 it should only have the standard script controls image 2

**Screenshots**
image
image

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- OpenC3 COSMOS Version 5.9.0
- Browser
  -- [] Internet Explorer (IE)
  -- [X] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #746

### CODE REVIEW

File: openc3/lib/openc3/utilities/local_mode.rb [hunk 1]
```diff
@@ -431,7 +431,7 @@ def self.sync_tool_config()
             # Parse just to ensure we have valid JSON
             JSON.parse(data, :allow_nan => true, :create_additions => true)
             # Only save if the parse was successful
-            ToolConfigModel.save_config(parts[-2], File.basename(config), data, scope: scope, local_mode: false)
+            ToolConfigModel.save_config(parts[-2], File.basename(config, '.json'), data, scope: scope, local_mode: false)
```
Comment (jmthomas) [inline openc3/lib/openc3/utilities/local_mode.rb:434]: Is this the fix for the weird config save where the name didn't have an extension?

File: scripts/linux/openc3_util.sh [hunk 2]
```diff
@@ -150,9 +150,17 @@ case $1 in
...
+      echo "Usage: hostsetup <REPO> <NAMESPACE> <TAG>" >&2
+      echo "e.g. hostsetup docker.io openc3inc latest" >&2
+      exit 1
+    fi
+    repo=$2
+    namespace=$3
+    tag=$4
+    docker run --rm --privileged --pid=host --entrypoint='' --user root $repo/$namespace/openc3-operator:$tag nsenter -t 1 -m -u -n -i -- sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
+    docker run --rm --privileged --pid=host --entrypoint='' --user root $repo/$namespace/openc3-operator:$tag nsenter -t 1 -m -u -n -i -- sh -c "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
+    docker run --rm --privileged --pid=host --entrypoint='' --user root $repo/$namespace/openc3-operator:$tag nsenter -t 1 -m -u -n -i -- sh -c "sysctl -w vm.max_map_count=262144"
```
Comment (jmthomas) [inline scripts/linux/openc3_util.sh:163]: No more justincormack?

File: openc3/lib/openc3/utilities/local_mode.rb (hunk 1 above)
Comment (ryanmelt) [reply openc3/lib/openc3/utilities/local_mode.rb:434]: Config files were being synced in the init container with names like "myconfig.json".  
But when you save them in tools you just type myconfig.   It was causing a duplication with a different name at restart.  Config names now consistently don't include .json, but the files obviously do.
