### PR TITLE
inject_tlm performed by microservices

### LINKED ISSUE #518: inject_tlm invalidated due to not providing packet_time
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
inject_tlm is causing a NoMethodError.

This is due to the fact that the telemetry_topic is now expecting the attribute of packet_time but inject_tlm never populates that attribute so it is nil at the time it attempts to write to the telemetry topic line 29

**To Reproduce**
Use the inject_tlm method

**Expected behavior**
inject_tlm should inject the telemetry of the target, packet, hash provided

**Suggested fixes**
I suggest maybe tlm_api.rb around line 152 to define the packet_time. This packet_time should include any potential derived conversion be applied to it if it is declared in the definitions.

**Screenshots**
/usr/lib/ruby/gems/3.1.0/gems/openc3-5.5.0/lib/openc3/topics/telemetry_topic.rb:29:in `write_packet': undefined method `to_nsec_from_epoch' for nil:NilClass (NoMethodError)

        :time => packet.packet_time.to_nsec_from_epoch,
                                   ^^^^^^^^^^^^^^^^^^^

**Environment (please complete the following information):**

- OS: Windows 10
- OpenC3 COSMOS Version 5.5.0
- Browser
  -- [] Internet Explorer (IE)
  -- [X] Google Chrome
  -- [] Chromium based browsers
  -- [] Mozilla Firefox
  -- [] Safari

### PR DESCRIPTION
**Pull request by ryanmelt**
also repair interface_cmd, protocol_cmd, and router commanding
closes #518

### CODE REVIEW

File: openc3/lib/openc3/api/tlm_api.rb [hunk 1]
```diff
@@ -135,22 +137,21 @@ def inject_tlm(target_name, packet_name, item_hash = nil, type: :CONVERTED, scop
...
-      msg_id, msg_hash = Topic.get_newest_message(topic)
-      if msg_id
-        packet.received_count = msg_hash['received_count'].to_i + 1
+
+      # Use an interface microservice if it exists, other use the decom microservice
+      if interface_name
+        InterfaceTopic.inject_tlm(interface_name, target_name, packet_name, item_hash, type: type, scope: scope)
       else
-        packet.received_count = 1
+        DecomTopic.inject_tlm(target_name, packet_name, item_hash, type: type, scope: scope)
```
Comment (jmthomas) [inline openc3/lib/openc3/api/tlm_api.rb:153]: Most targets have interfaces but if not we use Decom which is always deployed for each packet. What does the use of the Interface get you over Decom?

Comment (ryanmelt) [reply openc3/lib/openc3/api/tlm_api.rb:153]: Its a matter of who is keeping track of received_count

File: openc3/lib/openc3/interfaces/interface.rb [hunk 2]
```diff
@@ -501,19 +501,46 @@ def interface_cmd(cmd_name, *cmd_args)
...
       handled = false
-      protocols.each_with_index do |protocol, protocol_index|
-        result = protocol.protocol_cmd(cmd_name, @cmd_args) if index == protocol_index or index == -1
-        handled = true if result
+
+      if index >= 0 or read_write == :READ_WRITE
+        # Reconstruct full list of protocols in correct order
+        protocols = []
+        read_protocols = @read_protocols
+        write_protocols = @write_protocols.reverse
```
Comment (jmthomas) [inline openc3/lib/openc3/interfaces/interface.rb:511]: So the bug was not reversing the write_protocols when iterating through

File: openc3/lib/openc3/interfaces/interface.rb [hunk 3]
```diff
@@ -501,19 +501,46 @@ def interface_cmd(cmd_name, *cmd_args)
...
+            read_index += 1
+          when :WRITE
+            protocols << write_protocols[write_index]
+            write_index += 1
+          when :READ_WRITE, :PARAMS
+            protocols << read_protocols[read_index]
+            read_index += 1
+            write_index += 1
+          end
+        end
```
Comment (jmthomas) [inline openc3/lib/openc3/interfaces/interface.rb:527]: So the bug was not building up the list according to their type. Previously it would have gone through all whether they were :READ or :WRITE.

File: openc3/lib/openc3/microservices/decom_microservice.rb [hunk 4]
```diff
@@ -21,15 +21,23 @@
...
   class DecomMicroservice < Microservice
+    include InterfaceDecomCommon
+
     def initialize(*args)
       super(*args)
+      # Should only be one target, but there might be multiple decom microservices for a given target
+      # First Decom microservice has no number in the name
+      if @name =~ /__DECOM__/
+        @topics << "#{scope}__DECOMINTERFACE__{#{@target_names[0]}}"
+      end
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/decom_microservice.rb:40]: This is a new topic dedicated to doing inject_tlm

File: openc3/lib/openc3/microservices/decom_microservice.rb [hunk 5]
```diff
@@ -47,9 +55,16 @@ def run
             Topic.read_topics(@topics) do |topic, msg_id, msg_hash, redis|
               break if @cancel_thread
 
-              decom_packet(topic, msg_id, msg_hash, redis)
+              if topic =~ /__DECOMINTERFACE/
+                if msg_hash.key?('inject_tlm')
+                  handle_inject_tlm(msg_hash['inject_tlm'])
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/decom_microservice.rb:60]: Seems like `__DECOMINTERFACE__` is a dedicated topic for inject_tlm. Is there a reason to check the msg_hash for inject_tlm? Is this going to be used for something else?

File: openc3/lib/openc3/microservices/interface_microservice.rb [hunk 6]
```diff
@@ -164,7 +171,7 @@ def run
                 if target_name
                   command = System.commands.identify(cmd_buffer, [target_name])
                 else
-                  command = System.commands.identify(cmd_buffer, @cmd_target_names)
+                  command = System.commands.identify(cmd_buffer, @interface.cmd_target_names)
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/interface_microservice.rb:174]: This is just a straight up bug. How have we never hit this before? And therefore is it even necessary?

File: openc3/lib/openc3/microservices/router_microservice.rb [hunk 7]
```diff
@@ -25,16 +25,15 @@
...
       if !packet.identified?
         # Need to identify so we can find the target
-        identified_packet = System.commands.identify(packet.buffer(false), @cmd_target_names)
+        identified_packet = System.commands.identify(packet.buffer(false), @interface.cmd_target_names)
         packet = identified_packet if identified_packet
       end
 
       begin
-        RouterTopic.route_command(packet, @cmd_target_names, scope: @scope)
+        RouterTopic.route_command(packet, @interface.cmd_target_names, scope: @scope)
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/router_microservice.rb:36]: So this was just getting rescued and logging errors.

File: openc3/lib/openc3/microservices/router_microservice.rb [hunk 8]
```diff
@@ -25,16 +25,15 @@
 module OpenC3
   class RouterMicroservice < InterfaceMicroservice
     def handle_packet(packet)
-      @count += 1
       RouterStatusModel.set(@interface.as_json(:allow_nan => true), scope: @scope)
       if !packet.identified?
         # Need to identify so we can find the target
-        identified_packet = System.commands.identify(packet.buffer(false), @cmd_target_names)
+        identified_packet = System.commands.identify(packet.buffer(false), @interface.cmd_target_names)
```
Comment (jmthomas) [inline openc3/lib/openc3/microservices/router_microservice.rb:31]: I guess all packets are identified because otherwise this would have crashed the router.

File: openc3/lib/openc3/topics/decom_topic.rb [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU Affero General Public License for more details.
+#
+# This file may also be used under the terms of a commercial license
+# if purchased from OpenC3, Inc.
+
+require 'openc3/topics/topic'
+
+module OpenC3
+  class DecomTopic < Topic
```
Comment (jmthomas) [inline openc3/lib/openc3/topics/decom_topic.rb:22]: We have CommandDecomTopic and TelemetryDecomTopic ... should this be InterfaceDecomTopic?

**Review by jmthomas — APPROVED** [review]

File: openc3/lib/openc3/interfaces/interface.rb (hunk 3 above)
Comment (ryanmelt) [reply openc3/lib/openc3/interfaces/interface.rb:527]: The real bug was not command WRITE protocols if READ_WRITE was specified.  READ_WRITE is suppose to be effectively all for protocols

File: openc3/lib/openc3/microservices/decom_microservice.rb (hunk 5 above)
Comment (ryanmelt) [reply openc3/lib/openc3/microservices/decom_microservice.rb:60]: Just inject_tlm for now.  Might be other things in the future.

File: openc3/lib/openc3/microservices/interface_microservice.rb (hunk 6 above)
Comment (ryanmelt) [reply openc3/lib/openc3/microservices/interface_microservice.rb:174]: This code is needed if not using the PREIDENTIFIED interface

File: openc3/lib/openc3/microservices/router_microservice.rb (hunk 7 above)
Comment (ryanmelt) [reply openc3/lib/openc3/microservices/router_microservice.rb:80]: Yep

File: openc3/lib/openc3/microservices/router_microservice.rb (hunk 8 above)
Comment (ryanmelt) [reply openc3/lib/openc3/microservices/router_microservice.rb:31]: Yes, when we are using the PREIDENTIFIED protocol

File: openc3/lib/openc3/topics/decom_topic.rb (hunk 9 above)
Comment (ryanmelt) [reply openc3/lib/openc3/topics/decom_topic.rb:22]: Good point. I should just put this in TelemetryDecomTopic
