### PR TITLE
Display binary encoded strings and BLOCK data

### LINKED ISSUE #342: wait_check silently fails with binary data
Running this script:

    data = "\xFF" * 10
    cmd("INST", "MEMLOAD", "DATA" => data)
    wait_check("INST HEALTH_STATUS BLOCKTEST == '#{data}'", 5)
    val = tlm("INST HEALTH_STATUS BLOCKTEST")
    puts val.formatted

Produces the following output:

    2022/12/15 21:21:35.657 (SCRIPTRUNNER): Script completed: 2022_12_15_15_21_11_205_temp.rb
    2022/12/15 21:21:35.656 (2022_12_15_15_21_11_205_temp.rb:6): 00000000: FF FF FF FF FF FF FF FF FF FF
    2022/12/15 21:21:34.681 (2022_12_15_15_21_11_205_temp.rb:3): cmd("INST MEMLOAD with DATA BINARY")
    2022/12/15 21:21:34.451 (SCRIPTRUNNER): Starting script: 2022_12_15_15_21_11_205_temp.rb

Note there is no output for the wait_check. While it's not correct to check binary data against a string, this should produce an error and not simply go by without any output.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #342

### CODE REVIEW

File: openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DetailsDialog.vue [hunk 1]
```diff
@@ -243,6 +243,43 @@ export default {
                 `${this.targetName}__${this.packetName}__${this.itemName}__WITH_UNITS`,
               ])
               .then((values) => {
+                for (var i = 0; i < values.length; i++) {
+                  let rawString = null
+                  // Check for raw encoded strings (non-ascii)
+                  if (
+                    values[i][0]['json_class'] == 'String' &&
```
Comment (ryanmelt) [inline openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DetailsDialog.vue:250]: Should all this logic use the === and !== versions?

Comment (ryanmelt) [reply openc3-cosmos-init/plugins/packages/openc3-tool-common/src/components/DetailsDialog.vue:250]: Comment applys througout

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Good fix to CvtModel.   Just need to adjust javascript comparision operators.

**Review by ryanmelt — APPROVED** [review]
